Rebuild EnigmaJS
scrtlabs/enigma-contract pull request #197
Opened 2020-01-07 14:11 UTC by assafmo

2020-01-07 15:32 UTC, lacabra approved these changes

2020-01-07 15:33 UTC, lacabra requested changes
Please include a description for this PR :)

2020-01-09 17:52 UTC, lacabra requested changes
I disagree with 447a7b0. The `migrate` is needed because `yarn build` includes `yarn test` which requires the `ganache-cli` running and the contracts migrated to run the tests.

2020-01-09 18:12 UTC, assafmo commented
> I disagree with [447a7b0](https://github.com/enigmampc/enigma-contract/commit/447a7b0b56fda615221f56a40dd2501a73270c4d). The `migrate` is needed because `yarn build` includes `yarn test` which requires the `ganache-cli` running and the contracts migrated to run the tests.

@lacabra Thanks, fixed it.

2020-01-09 18:27 UTC, lacabra approved these changes

2020-01-09 18:33 UTC, merged